# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c47842518cb737617aaadad1d5d2977d4ed6f7157d23bda03a15f37ee4fd8a1a839d7b29d8b8bbaad603a80927699a9b3d60b244d08d85091cdd50930b2b11b

test:
  secret_key_base: 81546b4dbc04898338f79974e7e065e2a0c0bfbf17882b64ba995bfbe27627380a4243bb444c98b12e95b68b044c1098e16031677f91c7c2ff37be30a7f1ccf8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
